syntax = "proto3";

package mage.proto;

option java_package = "mage.proto";
option java_outer_classname = "MageProtos";
option java_multiple_files = true;

message UUID {
  string value = 1;
}

message Timestamp {
  int64 millis = 1;
}

message MageVersion {
  int32 major = 1;
  int32 minor = 2;
  int32 patch = 3;
  string info = 4;
}

enum PlayerType {
  PLAYER_TYPE_UNSPECIFIED = 0;
  PLAYER_TYPE_HUMAN = 1;
  PLAYER_TYPE_COMPUTER_MAD = 2;
  PLAYER_TYPE_COMPUTER_SIMPLE = 3;
  PLAYER_TYPE_COMPUTER_MONTE_CARLO = 4;
  PLAYER_TYPE_COMPUTER_DRAFT_BOT = 5;
}

enum ManaType {
  MANA_TYPE_UNSPECIFIED = 0;
  MANA_TYPE_WHITE = 1;
  MANA_TYPE_BLUE = 2;
  MANA_TYPE_BLACK = 3;
  MANA_TYPE_RED = 4;
  MANA_TYPE_GREEN = 5;
  MANA_TYPE_COLORLESS = 6;
  MANA_TYPE_GENERIC = 7;
}

enum PlayerAction {
  PLAYER_ACTION_UNSPECIFIED = 0;
  PLAYER_ACTION_PASS_PRIORITY = 1;
  PLAYER_ACTION_PASS_PRIORITY_UNTIL_NEXT_TURN = 2;
  PLAYER_ACTION_PASS_PRIORITY_UNTIL_TURN_END_STEP = 3;
  PLAYER_ACTION_PASS_PRIORITY_UNTIL_NEXT_TURN_SKIP_STACK = 4;
  PLAYER_ACTION_PASS_PRIORITY_UNTIL_NEXT_MAIN_PHASE = 5;
  PLAYER_ACTION_PASS_PRIORITY_UNTIL_NEXT_END_STEP = 6;
  PLAYER_ACTION_PASS_PRIORITY_UNTIL_MY_NEXT_TURN = 7;
  PLAYER_ACTION_PASS_PRIORITY_UNTIL_END_STEP_BEFORE_MY_NEXT_TURN = 8;
  PLAYER_ACTION_PASS_PRIORITY_UNTIL_STACK_RESOLVED = 9;
  PLAYER_ACTION_PASS_PRIORITY_CANCEL_ALL_ACTIONS = 10;
  PLAYER_ACTION_UNDO = 11;
  PLAYER_ACTION_CONCEDE = 12;
  PLAYER_ACTION_MANA_AUTO_PAYMENT_ON = 13;
  PLAYER_ACTION_MANA_AUTO_PAYMENT_OFF = 14;
  PLAYER_ACTION_MANA_AUTO_PAYMENT_RESET = 15;
  PLAYER_ACTION_ADD_PERMISSION_TO_ROLLBACK_TURN = 16;
  PLAYER_ACTION_DENY_PERMISSON_TO_ROLLBACK_TURN = 17;
  PLAYER_ACTION_ROLLBACK_TURNS = 18;
  PLAYER_ACTION_REQUEST_PERMISSION_TO_SEE_HAND_CARDS = 19;
  PLAYER_ACTION_REVOKE_PERMISSIONS_TO_SEE_HAND_CARDS = 20;
  PLAYER_ACTION_ADD_PERMISSION_TO_SEE_HAND_CARDS = 21;
  PLAYER_ACTION_TRIGGER_AUTO_ORDER_ABILITY_FIRST = 22;
  PLAYER_ACTION_TRIGGER_AUTO_ORDER_ABILITY_LAST = 23;
  PLAYER_ACTION_TRIGGER_AUTO_ORDER_RESET_ALL = 24;
  PLAYER_ACTION_REQUEST_AUTO_ANSWER_ID_YES = 25;
  PLAYER_ACTION_REQUEST_AUTO_ANSWER_ID_NO = 26;
  PLAYER_ACTION_REQUEST_AUTO_ANSWER_TEXT_YES = 27;
  PLAYER_ACTION_REQUEST_AUTO_ANSWER_TEXT_NO = 28;
  PLAYER_ACTION_REQUEST_AUTO_ANSWER_RESET_ALL = 29;
  PLAYER_ACTION_HOLD_PRIORITY = 30;
  PLAYER_ACTION_UNHOLD_PRIORITY = 31;
  PLAYER_ACTION_PICTURE_AS_FOIL = 32;
  PLAYER_ACTION_PICTURE_AS_NON_FOIL = 33;
}

enum Zone {
  ZONE_UNSPECIFIED = 0;
  ZONE_HAND = 1;
  ZONE_GRAVEYARD = 2;
  ZONE_LIBRARY = 3;
  ZONE_BATTLEFIELD = 4;
  ZONE_STACK = 5;
  ZONE_EXILED = 6;
  ZONE_ALL = 7;
  ZONE_OUTSIDE = 8;
  ZONE_COMMAND = 9;
}

enum CardType {
  CARD_TYPE_UNSPECIFIED = 0;
  CARD_TYPE_ARTIFACT = 1;
  CARD_TYPE_CONSPIRACY = 2;
  CARD_TYPE_CREATURE = 3;
  CARD_TYPE_DUNGEON = 4;
  CARD_TYPE_ENCHANTMENT = 5;
  CARD_TYPE_INSTANT = 6;
  CARD_TYPE_KINDRED = 7;
  CARD_TYPE_LAND = 8;
  CARD_TYPE_PHENOMENON = 9;
  CARD_TYPE_PLANE = 10;
  CARD_TYPE_PLANESWALKER = 11;
  CARD_TYPE_SCHEME = 12;
  CARD_TYPE_SORCERY = 13;
  CARD_TYPE_VANGUARD = 14;
  CARD_TYPE_BATTLE = 15;
}

enum SuperType {
  SUPER_TYPE_UNSPECIFIED = 0;
  SUPER_TYPE_BASIC = 1;
  SUPER_TYPE_ELITE = 2;
  SUPER_TYPE_HOST = 3;
  SUPER_TYPE_LEGENDARY = 4;
  SUPER_TYPE_ONGOING = 5;
  SUPER_TYPE_SNOW = 6;
  SUPER_TYPE_WORLD = 7;
}

enum Rarity {
  RARITY_UNSPECIFIED = 0;
  RARITY_LAND = 1;
  RARITY_COMMON = 2;
  RARITY_UNCOMMON = 3;
  RARITY_RARE = 4;
  RARITY_MYTHIC = 5;
  RARITY_SPECIAL = 6;
  RARITY_BONUS = 7;
}

message ObjectColor {
  bool is_white = 1;
  bool is_blue = 2;
  bool is_black = 3;
  bool is_red = 4;
  bool is_green = 5;
}

enum SkillLevel {
  SKILL_LEVEL_UNSPECIFIED = 0;
  SKILL_LEVEL_BEGINNER = 1;
  SKILL_LEVEL_CASUAL = 2;
  SKILL_LEVEL_SERIOUS = 3;
}

enum MessageColor {
  MESSAGE_COLOR_UNSPECIFIED = 0;
  MESSAGE_COLOR_BLACK = 1;
  MESSAGE_COLOR_RED = 2;
  MESSAGE_COLOR_GREEN = 3;
  MESSAGE_COLOR_BLUE = 4;
  MESSAGE_COLOR_ORANGE = 5;
  MESSAGE_COLOR_YELLOW = 6;
}

enum MessageType {
  MESSAGE_TYPE_UNSPECIFIED = 0;
  MESSAGE_TYPE_USER_INFO = 1;
  MESSAGE_TYPE_STATUS = 2;
  MESSAGE_TYPE_GAME = 3;
  MESSAGE_TYPE_TALK = 4;
  MESSAGE_TYPE_WHISPER_FROM = 5;
  MESSAGE_TYPE_WHISPER_TO = 6;
}

enum SoundToPlay {
  SOUND_UNSPECIFIED = 0;
  SOUND_PLAYER_LEFT = 1;
  SOUND_PLAYER_QUIT_TOURNAMENT = 2;
  SOUND_PLAYER_SUBMITTED_DECK = 3;
  SOUND_PLAYER_WHISPERED = 4;
}

enum FrameStyle {
  FRAME_STYLE_UNSPECIFIED = 0;
  FRAME_STYLE_M15_NORMAL = 1;
  FRAME_STYLE_ZEN_FULL_ART_BASIC = 2;
  FRAME_STYLE_UNH_FULL_ART_BASIC = 3;
  FRAME_STYLE_UST_FULL_ART_BASIC = 4;
  FRAME_STYLE_BFZ_FULL_ART_BASIC = 5;
  FRAME_STYLE_INVENTIONS_FULL_ART = 6;
  FRAME_STYLE_INVOCATIONS_FULL_ART = 7;
  FRAME_STYLE_EXPEDITION_FULL_ART = 8;
  FRAME_STYLE_UGL_FULL_ART_BASIC = 9;
  FRAME_STYLE_M21_SHOWCASE_BASIC = 10;
  FRAME_STYLE_SLD_FULL_ART_BASIC = 11;
}

enum ArtRect {
  ART_RECT_UNSPECIFIED = 0;
  ART_RECT_NORMAL = 1;
  ART_RECT_SPLIT_LEFT = 2;
  ART_RECT_SPLIT_RIGHT = 3;
  ART_RECT_SPLIT_FUSED = 4;
  ART_RECT_AFTERMATH_TOP = 5;
  ART_RECT_AFTERMATH_BOTTOM = 6;
  ART_RECT_TOKEN = 7;
}

enum AbilityType {
  ABILITY_TYPE_UNSPECIFIED = 0;
  ABILITY_TYPE_PLAY_CARD = 1;
  ABILITY_TYPE_SPELL = 2;
  ABILITY_TYPE_ACTIVATED = 3;
  ABILITY_TYPE_STATIC = 4;
  ABILITY_TYPE_TRIGGERED = 5;
  ABILITY_TYPE_MANA = 6;
  ABILITY_TYPE_EVASION = 7;
  ABILITY_TYPE_LOYALTY = 8;
  ABILITY_TYPE_SPECIAL = 9;
}

enum MageObjectType {
  MAGE_OBJECT_TYPE_UNSPECIFIED = 0;
  MAGE_OBJECT_TYPE_NULL = 1;
  MAGE_OBJECT_TYPE_CARD = 2;
  MAGE_OBJECT_TYPE_PERMANENT = 3;
  MAGE_OBJECT_TYPE_SPELL = 4;
  MAGE_OBJECT_TYPE_COPY_CARD = 5;
  MAGE_OBJECT_TYPE_TOKEN = 6;
  MAGE_OBJECT_TYPE_EMBLEM = 7;
  MAGE_OBJECT_TYPE_COMMANDER = 8;
  MAGE_OBJECT_TYPE_PLANE = 9;
  MAGE_OBJECT_TYPE_DUNGEON = 10;
  MAGE_OBJECT_TYPE_DESIGNATION = 11;
  MAGE_OBJECT_TYPE_ABILITY_STACK = 12;
  MAGE_OBJECT_TYPE_PLAYER = 13;
}

message PlayableObjectStats {
  int32 playable_amount = 1;
  bool playable_alternative = 2;
}

message CardIcon {
  string icon_type = 1;
  string hint = 2;
  string text = 3;
  int32 value = 4;
}
